seed = 1234
epochs = 10000
learning_rate = 2e-4
betas = [0.8, 0.99]
eps = 1e-9
batch_size = 32
fp16_run = false
lr_decay = 0.999875
segment_size = 8192
init_lr_ratio = 1.0
warmup_epochs = 0
c_mel = 45
c_kl = 1.0
# grad_clip = null

# min_seq_length = null
# max_seq_length = null

# min_spec_length = null
# max_spec_length = null

# min_speaker_utterances = null

last_epoch = 1
global_step = 1
